version: '3.8'

services:
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    image: ollama/ollama
    container_name: ollama-prod
    restart: unless-stopped
    # ports:
      # - "11434:11434" # no exponerlo al exterior
    volumes:
      - ollama_data:/root/.ollama
  app:
    build: .
    container_name: containerai-prod
    restart: unless-stopped
    # ports:
    #   - "8000:8080" # Nginx se encarga de la comunicación
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
    depends_on: # asegurar que la app esté lista
      - app

volumes:
  ollama_data: